general:
  datasets_to_be_included: [ cocoesm, cocoms, cocout, emotions, pia, zpid ] # cocoesm, cocoms, cocout, emotions, pia, zpid
  log_dir: "../logs/check_pl_mac_features"  # only for preprocessing
  log_name: pl_mac_features

  steps:
    preprocessing: false
    analysis: false
    postprocessing: true

preprocessing:
  path_to_raw_data: "../data/raw"
  store_data: true  # only final data
  path_to_preprocessed_data: "../data/preprocessed"
  min_num_esm_measures: 5  # 5
  nrows: 999999 # only for descriptives
  need_inverse_coding: ["cocout", "emotions", "pia", "zpid", "cocoms"]  # all except cocoesm, do not change

  years_of_data_collection:
    cocoesm: [ 2021, 2022]
    cocoms: [ 2022, 2023]
    zpid: [ 2020 ]
    emotions: [ 2020 ]
    cocout: [ 2020, 2021 ]
    pia: [ 2021 ]

  sensing:
    app_substring:
      cocoms: "App_"
      zpid: "app_"
    call_substring:
      cocoms: "Call_totalDur"
      zpid: "phone_sum_dur_calls"
    call_reference:
      cocoms: "Screen_totalDur_unlocked"
      zpid: "screen_sum_dur_session"

  sanity_checking:
    sensing:
      nan_col_thresh: 0.15
      zero_col_thresh: 0.30

    nan_thresh: 0.3 # 30% NaNs -> warn
    cron_alpha_thresh: 0.6
    expected_pos_corrs:
    - self_esteem
    - social_status
    - trust_government
    - education_level
    - state_pa
    - trait_pa
    - sleep_quality_mean
    - number_interactions_mean
    - gdp_capita
    - state_wb
    - creative_imagination
    - productiveness
    - responsibility

    number_of_features:  # TODO This does currently not match (but all categories were checked) Ignore for now
      cocoesm: 149
      cocoms: 96
      cocout: 73
      emotions: 56
      pia: 42
      zpid: 67

analysis:
  load_data: true
  path_to_preprocessed_data: "../data/preprocessed"
  random_state: 42

  methods_to_apply:
    - select_samples
    - select_features
    - select_criterion
    - initial_info_log
    - drop_zero_variance_cols
    - create_pipeline
    - repeated_nested_cv
    - get_average_coefficients
    - store_analysis_results  # CAUTION

# for each combination, we will also use all samples and always compare it against the same samples using only pl
  feature_sample_combinations:
    # 1
    pl: [emotions, cocout, cocoesm, cocoms]
    srmc: [emotions, cocout, cocoesm, cocoms]
    sens: [zpid, cocoms]
    mac: [cocoesm]
    # 2  filter for "pl_" for comparisons
    pl_srmc: [emotions, cocout, cocoesm, cocoms]
    pl_sens: [zpid, cocoms]
    pl_srmc_sens: [cocoms]
    pl_mac: [cocoesm]
    # 3
    pl_srmc_mac: [cocoesm]
    # 4 all_in
    all_in: [cocoesm, cocout, cocoms, emotions, pia, zpid]

  no_control_lst: ["pl", "srmc", "sens", "mac", "all_in"] # we do not run control analyses for these combinations

  params: # adjusted by SLURM
    prediction_model: elasticnet  # elasticnet, randomforestregressor
    crit: state_wb  # state_wb, state_pa, state_na, trait_wb, trait_na, trait_pa
    feature_combination: pl_sens   # pl, srmc, sens, mac, pl_srmc, pl_sens, pl_srmc_sens, pl_mac, pl_srmc_mac, all_in
    samples_to_include: control   # all, selected, control

  cv:
    num_inner_cv: 3  # 10
    verbose_inner_cv: 0
    num_outer_cv: 3 # 10
    num_reps: 3  # 10
    id_grouping_col: other_unique_id
    cache_pipe: false  # not improving performance
    warm_start: false  # not improving performance

  crit_available: # not all criteria are available for all samples
    state_wb: [cocoesm, cocout, cocoms, emotions, pia, zpid]
    state_pa: [cocoesm, cocout, cocoms, emotions, pia]
    state_na: [cocoesm, cocout, cocoms, emotions, pia]
    trait_wb: [cocoesm, cocout, cocoms, pia, zpid]
    trait_pa: [cocoesm, cocout, cocoms, pia, zpid]
    trait_na: [cocoesm, cocout, cocoms, pia, zpid]

  imputation:
    num_imputations: 1  # 5
    max_iter: 1 # 40
    conv_thresh: 0.05  # 0.05  only RFR
    tree_max_depth: 10  # only RFR
    percentage_of_features: 0.5  # only ENR
    n_features_thresh: 50  # only ENR
    sample_posterior: False  # only ENR, use PMM instead
    pmm_k: 5  # number of neighbors to consider for PMM
    country_grouping_col: "other_country"
    years_col: "other_years_of_participation"

  scoring_metric:
    inner_cv_loop:
      name: neg_mean_squared_error
    outer_cv_loop: # only for evaluation in the outer loop, not for fitting, all tested
      - r2
      - neg_mean_squared_error
      - spearman

  model_hyperparameters:
    elasticnet:  # verify
      model__regressor__alpha: [0.1, 1]
      model__regressor__l1_ratio: [0, 1]
      #model__regressor__alpha: [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000, 100000]
      #model__regressor__l1_ratio: [0, 0.1, 0.2, 0.3, 0.4, 0.4, 0.6, 0.7, 0.8, 0.9, 1]
      #model__regressor__max_iter: [ 1000, 10000 ]
      #model__regressor__tol: [0.1, 0.01, 0.001, 0.0001]
    randomforestregressor:
      #model__regressor__max_depth: [4, 6]
      #model__regressor__max_features: [ 0.2 ]
      model__regressor__n_estimators: [ 100, 500 ]
      model__regressor__max_features: [ 0.25, 0.5, 0.75]
      model__regressor__max_depth: [4, 6, 8, 10, 12]
      model__regressor__min_samples_split: [5, 10, 15, 20]

  parallelize:
    parallelize_shap: true
    shap_n_jobs: 3
    parallelize_inner_cv: true
    inner_cv_n_jobs: 3
    parallelize_shap_ia_values: true
    shap_ia_values_n_jobs: 1
    parallelize_imputation_runs: true # either parallelize runs or columns, for n_cores < 10
    imputation_runs_n_jobs: 3
    joblib_backend: "threading"  # loky, threading  # for pc2, use threading, loky may crash in multi-node settings

  shap_ia_values:  # TODO Needs to be implemented based on our affordances
    comp_shap_ia_values: false
    min_order: 2  # min interaction order, we already got 1 (the normal SHAP values)
    max_order: 3  # max interaction order, one correspond to the normal SHAP values
    budget: x  # budget for computation


  output_path: "../results/local_tests"
  results_cluster_path: "../results/cluster_results_state_wb_selected_shap"
  output_filenames:
    performance: 'cv_results.json'
    shap_values: 'shap_values.pkl'  # contains shap_values, base_values, and data
    shap_ia_values: 'shap_ia_values.pkl'
    lin_model_coefs: 'lin_model_coefficients.json'

postprocessing:
  processed_output_path: "../results/cluster_results_processed_5_shap" # "../results/cluster_results_processed"
  significance_tests:
    output_path: "../results/significance_tests"
    alpha: .05
    metric: r2
    methods:
      - xxx


  plots:
    shap_importance_plot:
      prediction_model: elasticnet  # elasticnet, randomforestregressor
      crit: state_wb
      samples_to_include: selected
      first_col: ["pl", "srmc", "sens", "mac"]
      second_col: ["pl_srmc", "pl_sens", "pl_srmc_sens", "pl_mac"]
      third_col: ["pl_srmc_mac", "all_in"]





