general:
  datasets_to_be_included: [cocoesm]  # cocoesm, cocoms, cocout, emotions, pia, zpid
  log_dir: "../logs/logging"
  log_name: test_logging_15092024

preprocessing:
  path_to_raw_data: "../data/raw"
  path_to_preprocessed_data: "../data/preprocessed"
  min_num_esm_measures: 5
  nrows: 9999
  need_inverse_coding: ["cocout", "emotions", "pia", "zpid", "cocoms"]  # cocoesm ist schon rekodiert, der Rest nicht
  # joint id col -> ID is the index in every dataset
  sanity_checking:
    nan_thresh: 0.3  # 30% NaNs -> warn
    cron_alpha_thresh: 0.5
    expected_pos_corrs:
    - self_esteem
    - social_status
    - trust_government
    - education_level
    - pa_state
    - pa_trait
    - sleep_quality_mean
    - number_of_interactions_mean
    - gdp_capita


    number_of_features:  # as in PreReg Table, without sensing ye
      cocoesm: 139 # davon MAC 53
      cocoms: 84
      cocout: 64
      emotions: 50
      pia: 34
      zpid: 62



