category_names:
  pl: "Personal"
  srmc: "ESM"
  sens: "Sensing"
  mac: "Societal"

pl:
  sociability: "Sociability"
  assertiveness: "Assertiveness"
  energy_level: "Energy level"
  compassion: "Compassion"
  respectfulness: "Respectfulness"
  trust: "Trust"
  organization: "Organization"
  productiveness: "Productiveness"
  responsibility: "Responsibility"
  anxiety: "Anxiety"
  depression: "Depression"
  emotional_volatility: "Emotional volatility"
  intellectual_curiosity: "Intellectual curiosity"
  aesthetic_sensitivity: "Aesthetic sensitivity"
  creative_imagination: "Creative imagination"
  sincerity: "Sincerity"
  fairness: "Fairness"
  greed_avoidance: "Greed-avoidance"
  modesty: "Modesty"
  narcissistic_admiration: "Narcissistic admiration"
  narcissistic_rivalry: "Narcissistic rivalry"
  intimate_loneliness: "Intimate loneliness"
  relational_loneliness: "Relational loneliness"
  collective_loneliness: "Collective loneliness"
  self_esteem: "Self-esteem"
  self_distraction: "Self-distraction"
  active_coping: "Active coping"
  denial: "Denial"
  substance_use: "Substance use"
  emotional_support: "Use of emotional support"
  instrumental_support: "Use of instrumental support"
  behavioral_disengagement: "Behavioral disengagement"
  venting: "Venting"
  positive_reframing: "Positive reframing"
  planning: "Planning"
  humor: "Humor"
  acceptance: "Acceptance"
  religion: "Religion"
  self_blame: "Self-blame"
  gender_male: "Gender male"
  gender_female: "Gender female"
  gender_other: "Gender other"
  age: "Age"
  student: "Student (in school/university)"
  full_employed: "Full-time employed"
  part_employed: "Part-time employed"
  self_employed: "Entrepreneur/self-employed"
  unemployed: "Unemployed"
  education_level: "Education level"
  people_household: "Number of people living in household"
  living_alone: "Living alone"
  living_partner: "Living together with partner"
  living_children: "Living with children"
  living_other: "Living together with friends/flatmates/family"
  relationship: "In relationship (vs. single)"
  religiosity: "Religiosity"
  political_orientation: "Political orientation (left vs. right)"
  social_status: "Subjective social status"
  conspiracy_mentality: "Conspiracy mentality"
  trust_government: "Trust in government"
  economic_marginalization: "Economic marginalization"
  cultural_marginalization: "Cultural marginalization"
  political_marginalization: "Political marginalization"
  dominance_orientation: "Dominance orientation"
  egalitarianism: "Egalitarianism"
  aggressive_authoritarianism: "Aggressive authoritarianism"
  submissive_authoritarianism: "Submissive authoritarianism"
  conventionalist_authoritarianism: "Conventionalist authoritarianism"

srmc:
  number_interactions: "Absolute number of social interactions"
  percentage_interactions: "Percentage of social interactions"
  ftf_interactions: "Percentage of face-to-face interactions"
  close_interactions: "Percentage of close-tie interactions"
  work_conversations: "Percentage of conversations about work/studying topics"
  personal_conversations: "Percentage of conversations about personal/leisure topics"
  societal_conversations: "Percentage of conversations about societal topics"
  job_situations: "Percentage of job/university-related situations"
  number_interaction_partners_mean: "Mean number of interaction partners"
  number_interaction_partners_sd: "SD number of interaction partners"
  number_interaction_partners_min: "Min number of interaction partners"
  number_interaction_partners_max: "Max number of interaction partners"
  sleep_quality_mean: "Mean daily sleep quality"
  sleep_quality_sd: "SD daily sleep quality"
  sleep_quality_min: "Min daily sleep quality"
  sleep_quality_max: "Max daily sleep quality"
  home_office: "Percentage of days in home-office"
  weekday_responses: "Percentage of weekday responses"
  early_day_responses: "Percentage of responses before 3 pm"
  number_responses: "Total number of responses provided"
  percentage_responses: "Percentage of provided responses"

mac:
  power_distance: "Power distance"
  uncertainty_avoidance: "Uncertainty avoidance"
  individualism: "Individualism vs. collectivism"
  motivation_achievement: "Motivation towards achievement and success"
  shortterm_orientation: "Short- vs. long-term orientation"
  indulgance: "Indulgance vs. restraint"
  religiosity_index: "Religiosity index"
  political_rights: "Political rights"
  civil_liberties: "Civil liberties"
  democracy_index: "Democracy index"
  country_openness: "Country's openness"
  country_conscientiousness: "Country's conscientiousness"
  country_extraversion: "Country's extraversion"
  country_agreeableness: "Country's agreeableness"
  country_neuroticism: "Country's neuroticism"
  peacefulness: "Peacefulness"
  social_support: "Social support"
  trust_in_government: "Trust in government"
  social_spending: "Social spending"
  gender_gap: "Gender gap"
  population_estimates: "Population estimates"
  population_increases: "Population increases"
  population_density: "Population density"
  young_population: "Young population percentage"
  old_population: "Old population percentage"
  migrant_stock: "Migrant stock"
  number_refugees: "Number of refugees"
  asylum_applicants: "Number of asylum applicants"
  asylum_approvals: "Number of approved asylum applications"
  gdp_capita: "GDP per capita"
  gdp_growth: "GDP growth"
  income_inequality: "Income inequality"
  poverty_rate: "Poverty rate"
  stock_capitalization: "Stock market capitalization (% of GDP)"
  adult_unemployment: "Unemployment rate"
  youth_unemployment: "Youth unemployment rate"
  saving_rate: "Saving rate"
  inflation_rate: "Inflation rate"
  investments: "Gross fixed capital formation"
  household_income: "Household disposable income"
  fertility_rate: "Fertility rate"
  infant_mortality: "Infant mortality"
  life_expectancy: "Life expectancy"
  obesity_rates: "Obesity rates"
  healthcare_expenditure: "Healthcare expenditure per capita"
  access_water: "Access to clean water"
  health_dalys: "Disability-Adjusted Life Years (DALYs)"
  health_ylls: "Years of Life Lost (YLLs)"
  environmental_quality: "Environmental quality"
  air_pollution: "Air pollution"
  covid_infections: "Yearly COVID-19 infections"
  covid_vaccination: "COVID-19 vaccination coverage"
  daily_smokers: "Percentage of daily smokers"
  alcohol_consumption: "Alcohol consumption"

sens:
  smartphone_usage_mean: "Mean daily smartphone usage (unlocked)"
  smartphone_usage_sd: "SD daily smartphone usage (unlocked)"
  smartphone_usage_min: "Min daily smartphone usage (unlocked)"
  smartphone_usage_max: "Max daily smartphone usage (unlocked)"

  smartphone_activation_mean: "Mean daily smartphone activation (locked)"
  smartphone_activation_sd: "SD daily smartphone activation (locked)"
  smartphone_activation_min: "Min daily smartphone activation (locked)"
  smartphone_activation_max: "Max daily smartphone activation (locked)"

  phone_talking_mean: "Mean daily talking on the phone"
  phone_talking_sd: "Mean daily talking on the phone"
  phone_talking_min: "Mean daily talking on the phone"
  phone_talking_max: "Mean daily talking on the phone"

  first_usage_mean: "Mean first daily smartphone usage"
  first_usage_sd: "SD first daily smartphone usage"
  first_usage_min: "Min first daily smartphone usage"
  first_usage_max: "Max first daily smartphone usage"

  last_usage_mean: "Mean last daily smartphone usage"
  last_usage_sd: "SD last daily smartphone usage"
  last_usage_min: "Min last daily smartphone usage"
  last_usage_max: "Max last daily smartphone usage"

  audio_entertainment_apps_mean: "Mean daily audio entertainment apps usage"
  audio_entertainment_apps_sd: "SD daily audio entertainment apps usage"
  audio_entertainment_apps_min: "Min daily audio entertainment apps usage"
  audio_entertainment_apps_max: "Max daily audio entertainment apps usage"

  career_apps_mean: "Mean daily career apps usage"
  career_apps_sd: "SD daily career apps usage"
  career_apps_min: "Min daily career apps usage"
  career_apps_max: "Max daily career apps usage"

  communication_apps_mean: "Mean daily communication apps usage"
  communication_apps_sd: "SD daily communication apps usage"
  communication_apps_min: "Min daily communication apps usage"
  communication_apps_max: "Max daily communication apps usage"

  creativity_apps_mean: "Mean daily creativity apps usage"
  creativity_apps_sd: "SD daily creativity apps usage"
  creativity_apps_min: "Min daily creativity apps usage"
  creativity_apps_max: "Max daily creativity apps usage"

  dating_apps_mean: "Mean daily dating apps usage"
  dating_apps_sd: "SD daily dating apps usage"
  dating_apps_min: "Min daily dating apps usage"
  dating_apps_max: "Max daily dating apps usage"

  finance_apps_mean: "Mean daily finance apps usage"
  finance_apps_sd: "SD daily finance apps usage"
  finance_apps_min: "Min daily finance apps usage"
  finance_apps_max: "Max daily finance apps usage"

  food_apps_mean: "Mean daily food apps usage"
  food_apps_sd: "SD daily food apps usage"
  food_apps_min: "Min daily food apps usage"
  food_apps_max: "Max daily food apps usage"

  gaming_apps_mean: "Mean daily gaming apps usage"
  gaming_apps_sd: "SD daily gaming apps usage"
  gaming_apps_min: "Min daily gaming apps usage"
  gaming_apps_max: "Max daily gaming apps usage"

  health_apps_mean: "Mean daily health apps usage"
  health_apps_sd: "SD daily health apps usage"
  health_apps_min: "Min daily health apps usage"
  health_apps_max: "Max daily health apps usage"

  internet_apps_mean: "Mean daily internet apps usage"
  internet_apps_sd: "SD daily internet apps usage"
  internet_apps_min: "Min daily internet apps usage"
  internet_apps_max: "Max daily internet apps usage"

  knowledge_apps_mean: "Mean daily knowledge apps usage"
  knowledge_apps_sd: "SD daily knowledge apps usage"
  knowledge_apps_min: "Min daily knowledge apps usage"
  knowledge_apps_max: "Max daily knowledge apps usage"

  news_apps_mean: "Mean daily news apps usage"
  news_apps_sd: "SD daily news apps usage"
  news_apps_min: "Min daily news apps usage"
  news_apps_max: "Max daily news apps usage"

  orientation_apps_mean: "Mean daily orientation apps usage"
  orientation_apps_sd: "SD daily orientation apps usage"
  orientation_apps_min: "Min daily orientation apps usage"
  orientation_apps_max: "Max daily orientation apps usage"

  photo_apps_mean: "Mean daily photo apps usage"
  photo_apps_sd: "SD daily photo apps usage"
  photo_apps_min: "Min daily photo apps usage"
  photo_apps_max: "Max daily photo apps usage"

  reading_apps_mean: "Mean daily reading apps usage"
  reading_apps_sd: "SD daily reading apps usage"
  reading_apps_min: "Min daily reading apps usage"
  reading_apps_max: "Max daily reading apps usage"

  security_apps_mean: "Mean daily security apps usage"
  security_apps_sd: "SD daily security apps usage"
  security_apps_min: "Min daily security apps usage"
  security_apps_max: "Max daily security apps usage"

  settings_apps_mean: "Mean daily settings apps usage"
  settings_apps_sd: "SD daily settings apps usage"
  settings_apps_min: "Min daily settings apps usage"
  settings_apps_max: "Max daily settings apps usage"

  shopping_apps_mean: "Mean daily shopping apps usage"
  shopping_apps_sd: "SD daily shopping apps usage"
  shopping_apps_min: "Min daily shopping apps usage"
  shopping_apps_max: "Max daily shopping apps usage"

  social_media_apps_mean: "Mean daily social media apps usage"
  social_media_apps_sd: "SD daily social media apps usage"
  social_media_apps_min: "Min daily social media apps usage"
  social_media_apps_max: "Max daily social media apps usage"

  spirituality_apps_mean: "Mean daily spirituality apps usage"
  spirituality_apps_sd: "SD daily spirituality apps usage"
  spirituality_apps_min: "Min daily spirituality apps usage"
  spirituality_apps_max: "Max daily spirituality apps usage"

  time_apps_mean: "Mean daily time apps usage"
  time_apps_sd: "SD daily time apps usage"
  time_apps_min: "Min daily time apps usage"
  time_apps_max: "Max daily time apps usage"

  tools_apps_mean: "Mean daily tools apps usage"
  tools_apps_sd: "SD daily tools apps usage"
  tools_apps_min: "Min daily tools apps usage"
  tools_apps_max: "Max daily tools apps usage"

  transportation_apps_mean: "Mean daily transportation apps usage"
  transportation_apps_sd: "SD daily transportation apps usage"
  transportation_apps_min: "Min daily transportation apps usage"
  transportation_apps_max: "Max daily transportation apps usage"

  visual_entertainment_mean: "Mean daily visual entertainment apps usage"
  visual_entertainment_sd: "SD daily visual entertainment apps usage"
  visual_entertainment_min: "Min daily visual entertainment apps usage"
  visual_entertainment_max: "Max daily visual entertainment apps usage"

  weather_apps_mean: "Mean daily weather apps usage"
  weather_apps_sd: "SD daily weather apps usage"
  weather_apps_min: "Min daily weather apps usage"
  weather_apps_max: "Max daily weather apps usage"

  # Location and movement
  time_home_mean: "Mean daily time spent at home"
  time_home_sd: "SD daily time spent at home"
  time_home_min: "Min daily time spent at home"
  time_home_max: "Max daily time spent at home"

  time_work_mean: "Mean daily time spent at work/university"
  time_work_sd: "SD daily time spent at work/university"
  time_work_min: "Min daily time spent at work/university"
  time_work_max: "Max daily time spent at work/university"

  # Weather variables
  daily_temperature_mean: "Mean daily temperature"
  daily_temperature_sd: "SD daily temperature"
  daily_temperature_min: "Min daily temperature"
  daily_temperature_max: "Max daily temperature"

  daily_cloudcover_mean: "Mean daily cloud cover"
  daily_cloudcover_sd: "SD daily cloud cover"
  daily_cloudcover_min: "Min daily cloud cover"
  daily_cloudcover_max: "Max daily cloud cover"

  daily_precipation_mean: "Mean daily precipitation"
  daily_precipation_sd: "SD daily precipitation"
  daily_precipation_min: "Min daily precipitation"
  daily_precipation_max: "Max daily precipitation"

  daily_humidity_mean: "Mean daily humidity"
  daily_humidity_sd: "SD daily humidity"
  daily_humidity_min: "Min daily humidity"
  daily_humidity_max: "Max daily humidity"

  daily_uv_index_mean: "Mean daily UV index"
  daily_uv_index_sd: "SD daily UV index"
  daily_uv_index_min: "Min daily UV index"
  daily_uv_index_max: "Max daily UV index"

  daily_sunrise_mean: "Mean daily sunrise time"
  daily_sunrise_sd: "SD daily sunrise time"
  daily_sunrise_min: "Min daily sunrise time"
  daily_sunrise_max: "Max daily sunrise time"

  daily_sunset_mean: "Mean daily sunset time"
  daily_sunset_sd: "SD daily sunset time"
  daily_sunset_min: "Min daily sunset time"
  daily_sunset_max: "Max daily sunset time"

  # Physical activity variables
  total_distance_mean: "Mean daily total distance covered"
  total_distance_sd: "SD daily total distance covered"
  total_distance_min: "Min daily total distance covered"
  total_distance_max: "Max daily total distance covered"

  altitude_movement_mean: "Mean daily total altitude movement"
  altitude_movement_sd: "SD daily total altitude movement"
  altitude_movement_min: "Min daily total altitude movement"
  altitude_movement_max: "Max daily total altitude movement"

  time_foot_mean: "Mean daily time spent on foot"
  time_foot_sd: "SD daily time spent on foot"
  time_foot_min: "Min daily time spent on foot"
  time_foot_max: "Max daily time spent on foot"

  time_still_mean: "Mean daily time spent still"
  time_still_sd: "SD daily time spent still"
  time_still_min: "Min daily time spent still"
  time_still_max: "Max daily time spent still"

  time_vehicle_mean: "Mean daily time spent in vehicle"
  time_vehicle_sd: "SD daily time spent in vehicle"
  time_vehicle_min: "Min daily time spent in vehicle"
  time_vehicle_max: "Max daily time spent in vehicle"

  time_bicycle_mean: "Mean daily time spent on bicycle"
  time_bicycle_sd: "SD daily time spent on bicycle"
  time_bicycle_min: "Min daily time spent on bicycle"
  time_bicycle_max: "Max daily time spent on bicycle"

crit:
  wb_state: "State well-being"
  pa_state: "State positive affect"
  na_state: "State negative affect"
  wb_trait: "Trait well-being"
  pa_trait: "Trait positive affect"
  na_trait: "Trait negative affect"

  # cocoesm / cocoms
  state_pa1: "Happy"
  state_pa2: "Excited"
  state_pa3: "Relaxed"
  state_na1: "Angry"
  state_na2: "Anxious"
  state_na3: "Sad"
  panasx_4: "Happy"
  panasx_5: "Enthusiastic"
  panasx_6: "Relaxed"
  panasx_1: "Angry"
  panasx_2: "Anxious"
  panasx_3: "Sad"

  # cocout
  momentary_wellbeing_happy_ema: "Happy"
  momentary_wellbeing_angry_ema: "Angry"
  momentary_wellbeing_sad_ema: "Sad"
  momentary_wellbeing_worried_ema: "Worried"
  awb_3: "Happy"
  awb_5: "Enthusiastic"
  awb_6: "Relaxed"
  awb_1: "Angry"
  awb_2: "Worried"
  awb_4: "Sad"

  # emotions / pia
  happy: "Happy"
  relaxed: "Relaxed"
  enthusiastic: "Enthusiastic"
  angry: "Angry"
  sad: "Sad"
  anxious: "Anxious"
  afraid: "Anxious"
  panas13: "Enthusiastic"
  trait_happy: "Happy"
  trait_relaxed: "Relaxed"
  panas4: "Excited"
  trait_angry: "Angry"
  trait_sad: "Sad"
  panas20: "Anxious"

  # zpid
  valence: "Valence"
  PANAS_POS3: "A"
  PANAS_POS7: "B"
  PANAS_NEG1: "C"
  PANAS_NEG2: "D"
  PANAS_NEG10: "E"
